spring:
  datasource:
    oms:
      initialSize: 50
      maxActive: 500
      minIdle: 50
    report:
      initialSize: 1
      maxActive: 10
      minIdle: 0
    admin:
      initialSize: 5
      maxActive: 50
      minIdle: 1
    rds:
      initialSize: 1
      maxActive: 50
      minIdle: 0